### ISSUE TITLE
Warn user when browser features are missing

### ISSUE THREAD

**Issue by BarthPaleologue** [BarthPaleologue/CosmosJourneyer#201]
In firefox the keyboard layout detection is not supported. Using the new modal system to warn the user that QWERTY will be assumed is necessary.

**Comment by nakul-py** [comment]
Hi @BarthPaleologue 
I came across this issue and would like to work on resolving it. Could you please assign it to me?

**Comment by BarthPaleologue** [comment]
Hey there!

Thanks for taking an interest in the project! Let me know if you need any help to navigate the codebase ;)

**Comment by nakul-py** [comment]
You can close #203  pr if does'not mergable
