### ISSUE TITLE
Generate contributors image for credits

### ISSUE THREAD

**Issue by BarthPaleologue** [BarthPaleologue/CosmosJourneyer#209]
Generate a contributors image for the credits to showcase dynamically new contributors without needing any modifications.

The image from contrib.rocks should go in there: https://github.com/BarthPaleologue/CosmosJourneyer/blob/main/src/html/sidePanels.html#L49

And the styling should go somewhere in https://github.com/BarthPaleologue/CosmosJourneyer/blob/main/src/styles/mainMenu.scss

**Comment by nakul-py** [comment]
hey @BarthPaleologue will i takeover this issue

**Comment by BarthPaleologue** [comment]
Good to see you back so soon haha
