### ISSUE TITLE
Change default warp drive throttle to 50%

### ISSUE THREAD

**Issue by BarthPaleologue** [BarthPaleologue/CosmosJourneyer#230]
Right now the default throttle is 0%, but it could be confusing for new players as they might not understand they can change the throttle. By changing the default to 50%, it will be more obvious that the throttle is not to its maximum and hence can be modulated.

Implementation:

- In `WarpDrive`, create a readonly member `defaultThrottle` with value 0.5. 
- In `WarpDrive::enable`, set the throttle to `defaultThrottle`.

**Comment by nakul-py** [comment]
Hey @BarthPaleologue will you assign me this issue.

**Comment by BarthPaleologue** [comment]
Hey! Nice to see you again ^^ 

I just assigned you the issue, let me know if you need anything ;)
